name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_PASSWORD: 834000
  DEBUG: False
  ALLOWED_HOSTS: localhost 127.0.0.1 [::1]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: blog_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 834000
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until nc -z db 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          
      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:834000@localhost:5432/blog_db
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
